<div id="dhlparcel-shipping-modal-content">
    <div id="dhlparcel_shipping_locator_real_reset">
        <div id="dhl-servicepoint-locator-component"
         data-query=""
         data-limit="7"
         data-locale="<?=$block->escapeHtml($block->getLanguage())?>"
         data-setup="dhlparcel_shipping_reset_servicepoint"
         data-maps-key="<?=$block->escapeHtml($block->getGoogleMapsKey())?>"
        ></div>
    </div>
</div>
