<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php $_shipment = $block->getShipment() ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder() ?>
<?php if ($_shipment && $_order) : ?>
    <?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
    <?php if ($trackCollection) : ?>
        <br />
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($trackCollection as $_item) : ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <td>
                        <?php if ($_item->getCarrierCode() == "dhlparcel") : ?>
                            <?php $trackingUrl = $block->getDHLCarrier()->getTrackingUrl($_item->getNumber()); ?>
                        <?php endif; ?>

                        <?php if (isset($trackingUrl)) : ?>
                            <a href="<?php echo $trackingUrl; ?>"
                               onclick="this.target='_blank'">
                                <?= $block->escapeHtml($_item->getNumber()) ?>
                            </a>
                        <?php else : ?>
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
